# 阿里oss配置
alioss:
  accessKeyId: ''
  accessKeySecret: ''
  regionId: ''
  endpoint: ''
  bucket: ''
  roleArn: ''

# 数据库配置
db:
  mysql:
    host: '127.0.0.1'
    username: 'root'
    password: '123456'
    database: 'dgtle'
    port: 3306
    charset: 'utf8mb4'
    logger: 'file'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: false
    supportBigNumbers: true
    bigNumberStrings: true

# redis配置 keyPrefix 当存在多个服务连接同一个redis实例时使用
redis:
  type: 'single'
  options:
    host: '127.0.0.1'
    port: 6379
    password: ''
    db: 0
    keyPrefix: ''

# jwt 配置
jwt:
  secretkey: 'you_secretkey'
  expiresin: '1h'
  refreshExpiresIn: '2h'

# github 配置
github:
  clientId: ''
  clientSecret: ''

# 接口白名单
perm:
  router:
    whiteList:
      [
        { path: '/api/auth/captcha', method: 'GET' },
        { path: '/api/auth/login', method: 'POST' },
        { path: '/api/auth/registry', method: 'POST' },
        { path: '/api/upload/ossSign', method: 'GET' },
        { path: '/api/auth/github', method: 'GET' },
        { path: '/api/auth/github/callback', method: 'GET' },
      ]
